<a href="https://colab.research.google.com/github/Siddhant254/Deep-Learning-Concepts/blob/master/Backpropagation_using_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]] , columns = ['cgpa','profile_score','lpa'])
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# weights
model.get_weights()

[array([[-0.75840676, -0.6792462 ],
        [-0.7927319 ,  1.2226664 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.38028634],
        [-0.28987157]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=200,verbose=1,batch_size=1)

Epoch 1/200
4/4 [==============================] - 0s 5ms/step - loss: 16.9526
Epoch 2/200
4/4 [==============================] - 0s 7ms/step - loss: 16.7562
Epoch 3/200
4/4 [==============================] - 0s 5ms/step - loss: 16.5216
Epoch 4/200
4/4 [==============================] - 0s 9ms/step - loss: 16.2809
Epoch 5/200
4/4 [==============================] - 0s 7ms/step - loss: 16.0328
Epoch 6/200
4/4 [==============================] - 0s 5ms/step - loss: 15.8174
Epoch 7/200
4/4 [==============================] - 0s 8ms/step - loss: 15.5980
Epoch 8/200
4/4 [==============================] - 0s 9ms/step - loss: 15.3588
Epoch 9/200
4/4 [==============================] - 0s 9ms/step - loss: 15.1707
Epoch 10/200
4/4 [==============================] - 0s 9ms/step - loss: 14.9131
Epoch 11/200
4/4 [==============================] - 0s 8ms/step - loss: 14.7014
Epoch 12/200
4/4 [==============================] - 0s 9ms/step - loss: 14.4732
Epoch 13/200
4/4 [==============================]

In [ ]:
model.get_weights()

[array([[-0.64567506, -0.70261496],
        [-0.69778204,  1.2181163 ]], dtype=float32),
 array([ 0.10382751, -0.01259644], dtype=float32),
 array([[-0.25727308],
        [ 0.26779196]], dtype=float32),
 array([0.7210748], dtype=float32)]