<a href="https://colab.research.google.com/github/Siddhant254/Deep-Learning-Concepts/blob/master/Xavier_weight_Initialization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Data
from sklearn.datasets import make_classification

X,y = make_classification(n_samples=100,n_features=2,n_informative=1,n_redundant=0,
                          n_classes=2,n_clusters_per_class=1,random_state=41,hypercube=False,
                          class_sep=15)

In [3]:
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1])

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [7]:
model = Sequential()

model.add(Dense(10,activation='tanh',input_dim=2))
model.add(Dense(10,activation='tanh'))
model.add(Dense(10,activation='tanh'))
model.add(Dense(10,activation='tanh'))
model.add(Dense(1,activation='sigmoid'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 10)                110       
                                                                 
 dense_3 (Dense)             (None, 10)                110       
                                                                 
 dense_4 (Dense)             (None, 10)                110       
                                                                 
Total params: 470
Trainable params: 470
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.get_weights()

[array([[ 0.15830117, -0.45723733,  0.40134233,  0.3689726 , -0.3886548 ,
          0.26715827, -0.6293878 , -0.22787184, -0.36282888, -0.46048987],
        [ 0.10809755,  0.32077092,  0.16030252,  0.31660157, -0.22235563,
          0.3324619 ,  0.6500394 , -0.2072792 , -0.05484718,  0.6908322 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-6.79937601e-02,  2.46510446e-01, -1.81933999e-01,
          2.33097017e-01, -5.02080917e-01, -5.27280450e-01,
         -1.99459612e-01, -2.64433295e-01, -2.63401121e-01,
          1.34882331e-02],
        [-3.85391712e-03,  4.93492603e-01, -4.59889352e-01,
          2.00946331e-01,  1.48195863e-01,  1.21654153e-01,
          2.00169742e-01,  4.92469072e-01, -2.15538293e-01,
         -5.37676215e-01],
        [-5.10891736e-01, -9.40348208e-02, -4.64291573e-01,
          7.13381171e-02, -2.43944407e-01, -2.53973126e-01,
          3.02765608e-01,  5.14751673e-02,  4.05299723e-01,
         -1.7188689

In [11]:
initial_weights = model.get_weights()

In [12]:
initial_weights[0] = np.random.randn(2,10)*np.sqrt(1/2)
initial_weights[1] = np.zeros(model.get_weights()[1].shape)
initial_weights[2] = np.random.randn(10,10)*np.sqrt(1/10)
initial_weights[3] = np.zeros(model.get_weights()[3].shape)
initial_weights[4] = np.random.randn(10,10)*np.sqrt(1/10)
initial_weights[5] = np.zeros(model.get_weights()[5].shape)
initial_weights[6] = np.random.randn(10,10)*np.sqrt(1/10)
initial_weights[7] = np.zeros(model.get_weights()[7].shape)
initial_weights[8] = np.random.randn(10,1)*np.sqrt(1/10)
initial_weights[9] = np.zeros(model.get_weights()[9].shape)

In [13]:
model.set_weights(initial_weights)

In [14]:
model.get_weights()

[array([[ 0.36780143,  0.99820113, -0.32481384,  0.02804792, -0.4857819 ,
         -0.56341165, -0.09681994,  0.295071  , -0.77649885,  0.57366294],
        [ 0.07735323, -0.62532073, -0.8885564 , -0.17749259,  0.0331676 ,
         -0.00910983, -0.8123738 ,  0.03192174,  0.5637429 , -0.03312144]],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.5283748 , -0.04830331,  0.12914146,  0.64796567,  0.5655437 ,
          0.3404529 ,  0.2619143 ,  0.17142858,  0.4434382 ,  0.00898103],
        [-0.08953783, -0.30556288, -0.02321166, -0.55118346,  0.2740628 ,
         -0.16601147,  0.28534448, -0.14513837,  0.24204515, -0.15415041],
        [ 0.4954179 , -0.668405  , -0.1651946 ,  0.00753544,  0.22661437,
          0.5811115 , -0.24537677, -0.22729667, -0.5071941 , -0.2589317 ],
        [-0.30350822, -0.493816  , -0.02540888,  0.03268489, -0.337841  ,
         -0.09748012,  0.30907547,  0.2585804 ,  0.22874348, -0.07997647],
        [-0.39179

In [15]:
model.compile(loss = 'binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [16]:
history = model.fit(X,y,epochs=100,validation_split=0.2)

Epoch 1/100
3/3 [==============================] - 2s 132ms/step - loss: 0.6449 - accuracy: 0.8375 - val_loss: 0.6257 - val_accuracy: 0.8000
Epoch 2/100
3/3 [==============================] - 0s 30ms/step - loss: 0.6265 - accuracy: 0.8500 - val_loss: 0.6080 - val_accuracy: 0.8500
Epoch 3/100
3/3 [==============================] - 0s 19ms/step - loss: 0.6087 - accuracy: 0.8750 - val_loss: 0.5906 - val_accuracy: 0.8500
Epoch 4/100
3/3 [==============================] - 0s 18ms/step - loss: 0.5917 - accuracy: 0.8875 - val_loss: 0.5737 - val_accuracy: 0.9000
Epoch 5/100
3/3 [==============================] - 0s 19ms/step - loss: 0.5749 - accuracy: 0.9000 - val_loss: 0.5573 - val_accuracy: 0.9000
Epoch 6/100
3/3 [==============================] - 0s 20ms/step - loss: 0.5586 - accuracy: 0.9000 - val_loss: 0.5413 - val_accuracy: 0.9000
Epoch 7/100
3/3 [==============================] - 0s 19ms/step - loss: 0.5431 - accuracy: 0.9000 - val_loss: 0.5256 - val_accuracy: 0.9000
Epoch 8/100
3/3 [==